"""SVG debug-canvas renderer: evidence images from the SAME part tables that
emit the Swift constants.

These are evidence renders, not product surfaces: fills are placeholder
evidence tones (the pipeline is a build tool - R4 governs the shipped rig,
which stays colorless). Every SVG carries that disclaimer in a header
comment. Four canvases are produced:

  rig-full.svg        the full 21-constant rig (each part filled)
  rig-lod-glance.svg  the LOD-glance variant
  rig-glyph.svg       the glyph variant, with 24 pt / 32 pt legibility tiles
  room-scene.svg      room base + pom + the pet + the four props (the
                      evidence-only composition)
"""

import geometry as g

CANVAS = 1000

# Canvas-composition nudge for the evidence room scene (fix round 1, review
# O5): sparkleA's authored spot overlaps the window frame, which reads
# accidental. Translating it into the clear left-wall space (95 units clear
# of the window, 39 of the body). COMPOSITION ONLY - the sparkle prop's Path
# constants are untouched; render_evidence.swift carries the same delta.
SPARKLE_A_NUDGE = (-100.0, 310.0)

# Evidence-only placeholder tones (never shipped; the rig is colorless, R4).
TONE = {
    "background": "#FBF7F1",
    "fur": "#EDE3D4",
    "furShade": "#E2D5C2",
    "belly": "#F8F2E9",
    "eye": "#4A4038",
    "cheek": "#F0C6C0",
    "floor": "#EAE1D2",
    "rug": "#DCE4DB",
    "window": "#F6F1E8",
    "windowLight": "#FDFAF5",
    "pom": "#E7C9CD",
    "bowl": "#D8CDBD",
    "mound": "#BFB09A",
    "blanket": "#D8CCDF",
    "sparkle": "#EFD79A",
}

FILL_BY_PART = {
    "body": "fur", "head": "fur", "earLeft": "fur", "earRight": "fur",
    "tail": "furShade", "hindFootLeft": "furShade", "hindFootRight": "furShade",
    "pawLeft": "furShade", "pawRight": "furShade", "lodPawPair": "furShade",
    "lodBody": "fur", "lodHead": "fur", "lodEarLeft": "fur", "lodEarRight": "fur",
    "lodTail": "furShade", "lodHindFootLeft": "furShade",
    "lodHindFootRight": "furShade",
    "bellyPatch": "belly", "lodBellyPatch": "belly",
    "eyeLeftBase": "eye", "eyeRightBase": "eye", "lodEyeLeft": "eye",
    "lodEyeRight": "eye", "glyphEyeLeft": "eye", "glyphEyeRight": "eye",
    "eyeLeftPupil": "eye", "eyeRightPupil": "eye",
    "eyeLeftLid": "fur", "eyeRightLid": "fur",
    "mouthNeutral": "eye", "mouthEat": "eye", "mouthRefuse": "eye",
    "cheekLeft": "cheek", "cheekRight": "cheek",
    "glyphSilhouette": "furShade",
    "floor": "floor", "rug": "rug", "window": "window",
    "pomString": "furShade", "pomPuff": "pom",
    "food": "bowl", "blanket": "blanket",
    "sparkleA": "sparkle", "sparkleB": "sparkle",
}


def _path_data(subpath):
    cmds = []
    for seg in subpath:
        if seg[0] == "M":
            cmds.append("M %s %s" % (g.fmt(seg[1][0]), g.fmt(seg[1][1])))
        elif seg[0] == "L":
            cmds.append("L %s %s" % (g.fmt(seg[1][0]), g.fmt(seg[1][1])))
        elif seg[0] == "Q":
            cmds.append("Q %s %s %s %s" % (g.fmt(seg[1][0]), g.fmt(seg[1][1]),
                                           g.fmt(seg[2][0]), g.fmt(seg[2][1])))
        elif seg[0] == "C":
            cmds.append("C %s %s %s %s %s %s" % (
                g.fmt(seg[1][0]), g.fmt(seg[1][1]),
                g.fmt(seg[2][0]), g.fmt(seg[2][1]),
                g.fmt(seg[3][0]), g.fmt(seg[3][1])))
        elif seg[0] == "Z":
            cmds.append("Z")
    return " ".join(cmds)


def _shapes(parts, extra_transform=""):
    out = []
    for part in parts:
        for sp in part["subpaths"]:
            fill = TONE[FILL_BY_PART[part["name"]]]
            out.append(
                '<path transform="%s" d="%s" fill="%s"/>'
                % (extra_transform, _path_data(sp), fill)
                if extra_transform else
                '<path d="%s" fill="%s"/>' % (_path_data(sp), fill)
            )
    return out


def _svg(title, body):
    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
            'width="%d" height="%d">' % (CANVAS, CANVAS, CANVAS, CANVAS),
            "<!-- EVIDENCE RENDER - placeholder tones, not product tokens "
            "(the rig is colorless, R4). Generated by: "
            "python3 Tools/character-pipeline/generate.py --evidence-dir <dir> -->",
            "<!-- %s -->" % title,
            '<rect width="%d" height="%d" fill="%s"/>' % (CANVAS, CANVAS, TONE["background"]),
        ]
        + body
        + ["</svg>", ""]
    )


def _pet(parts_by_name):
    order = [
        "tail", "hindFootLeft", "hindFootRight", "body", "bellyPatch",
        "head", "earLeft", "earRight", "cheekLeft", "cheekRight",
        "mouthNeutral", "eyeLeftBase", "eyeLeftPupil", "eyeLeftLid",
        "eyeRightBase", "eyeRightPupil", "eyeRightLid",
        "pawLeft", "pawRight",
    ]
    return _shapes([parts_by_name[n] for n in order])


def rig_full_svg(by_name):
    return _svg("TASK-025 evidence: full rig (21 constants, 19 counted parts)",
                _pet(by_name))


def rig_lod_svg(by_name):
    order = [
        "lodTail", "lodHindFootLeft", "lodHindFootRight", "lodBody",
        "lodBellyPatch", "lodHead", "lodEarLeft", "lodEarRight",
        "lodEyeLeft", "lodEyeRight", "lodPawPair",
    ]
    return _svg("TASK-025 evidence: LOD-glance variant (11 constants - "
                "no pupil split, simplified paws)",
                _shapes([by_name[n] for n in order]))


def _glyph_tile(by_name, translate, scale):
    body = _shapes(
        [by_name["glyphSilhouette"], by_name["glyphEyeLeft"],
         by_name["glyphEyeRight"]],
        extra_transform="translate(%s %s) scale(%s)"
        % (g.fmt(translate[0]), g.fmt(translate[1]), g.fmt(scale)),
    )
    return body


def rig_glyph_svg(by_name):
    body = _glyph_tile(by_name, (0.0, 0.0), 1.0)
    # Legibility tiles at the AOD/complication sizes of 04 section 2.1:
    # 32 pt and 24 pt squares mapped into grid units (1 pt = 1000/1000
    # grid units per the stage table; tiles drawn at the canvas corner).
    body += _glyph_tile(by_name, (30.0, 30.0), 0.032)
    body += _glyph_tile(by_name, (90.0, 30.0), 0.024)
    return _svg("TASK-025 evidence: glyph variant (3 constants - ears merged "
                "into the silhouette; 24/32 pt tiles top-left)", body)


def room_scene_svg(by_name):
    room_order = ["floor", "rug", "window", "pomString", "pomPuff"]
    prop_order = ["food", "blanket"]
    body = _shapes([by_name[n] for n in room_order])
    body += _shapes([by_name[n] for n in prop_order])
    body += _pet(by_name)
    nudge = "translate(%s %s)" % (g.fmt(SPARKLE_A_NUDGE[0]), g.fmt(SPARKLE_A_NUDGE[1]))
    body += _shapes([by_name["sparkleA"]], extra_transform=nudge)
    body += _shapes([by_name["sparkleB"]])
    return _svg("TASK-025 evidence: room scene + props composed with the "
                "full rig (evidence-only composition)", body)


def render_all(by_name):
    return {
        "rig-full.svg": rig_full_svg(by_name),
        "rig-lod-glance.svg": rig_lod_svg(by_name),
        "rig-glyph.svg": rig_glyph_svg(by_name),
        "room-scene.svg": room_scene_svg(by_name),
    }
